name: Django CI UTF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Manually install Python 2.7 and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python-pip

      - name: Verify Python version
        run: python2.7 -V

      - name: Install dependencies
        run: |
          python2.7 -m pip install --upgrade pip
          python2.7 -m pip install -r requirements.txt

      - name: Check for non-ASCII characters
        run: |
          for file in $(find . -name "*.py"); do
            if grep -Pn "[^[:ascii:]]" $file; then
              echo "Non-ASCII characters found in $file!"
              exit 1
            fi
          done
          echo "No non-ASCII characters detected."
