name: Django CI UTF

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Manually install Python 2.7 and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python2.7 python-pip

      - name: Verify Python version
        run: python2.7 -V

      - name: Install dependencies
        run: |
          python2.7 -m pip install --upgrade pip
          python2.7 -m pip install -r requirements.txt

      - name: Check for non-ASCII characters
        run: |
          if find . -name "*.py" | xargs grep -Pn "[^[:ascii:]]"; then
            echo "Non-ASCII characters found!"
            exit 1
          else
            echo "No non-ASCII characters detected."
          fi
